// Code generated by protoc-gen-go. DO NOT EDIT.
// source: contextionary.proto

/*
Package contextionary is a generated protocol buffer package.

It is generated from these files:
	contextionary.proto

It has these top-level messages:
	Word
	WordPresent
	WordStopword
	Keyword
	SchemaSearchParams
	SchemaSearchResults
	SchemaSearchResult
*/
package contextionary

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchType int32

const (
	SearchType_CLASS    SearchType = 0
	SearchType_PROPERTY SearchType = 1
)

var SearchType_name = map[int32]string{
	0: "CLASS",
	1: "PROPERTY",
}
var SearchType_value = map[string]int32{
	"CLASS":    0,
	"PROPERTY": 1,
}

func (x SearchType) String() string {
	return proto.EnumName(SearchType_name, int32(x))
}
func (SearchType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Kind int32

const (
	Kind_THING  Kind = 0
	Kind_ACTION Kind = 1
)

var Kind_name = map[int32]string{
	0: "THING",
	1: "ACTION",
}
var Kind_value = map[string]int32{
	"THING":  0,
	"ACTION": 1,
}

func (x Kind) String() string {
	return proto.EnumName(Kind_name, int32(x))
}
func (Kind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Word struct {
	Word string `protobuf:"bytes,1,opt,name=word" json:"word,omitempty"`
}

func (m *Word) Reset()                    { *m = Word{} }
func (m *Word) String() string            { return proto.CompactTextString(m) }
func (*Word) ProtoMessage()               {}
func (*Word) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Word) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

type WordPresent struct {
	Present bool `protobuf:"varint,1,opt,name=present" json:"present,omitempty"`
}

func (m *WordPresent) Reset()                    { *m = WordPresent{} }
func (m *WordPresent) String() string            { return proto.CompactTextString(m) }
func (*WordPresent) ProtoMessage()               {}
func (*WordPresent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WordPresent) GetPresent() bool {
	if m != nil {
		return m.Present
	}
	return false
}

type WordStopword struct {
	Stopword bool `protobuf:"varint,1,opt,name=stopword" json:"stopword,omitempty"`
}

func (m *WordStopword) Reset()                    { *m = WordStopword{} }
func (m *WordStopword) String() string            { return proto.CompactTextString(m) }
func (*WordStopword) ProtoMessage()               {}
func (*WordStopword) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *WordStopword) GetStopword() bool {
	if m != nil {
		return m.Stopword
	}
	return false
}

type Keyword struct {
	Keyword string  `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
	Weight  float32 `protobuf:"fixed32,2,opt,name=weight" json:"weight,omitempty"`
}

func (m *Keyword) Reset()                    { *m = Keyword{} }
func (m *Keyword) String() string            { return proto.CompactTextString(m) }
func (*Keyword) ProtoMessage()               {}
func (*Keyword) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Keyword) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *Keyword) GetWeight() float32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

type SchemaSearchParams struct {
	SearchType SearchType `protobuf:"varint,1,opt,name=searchType,enum=contextionary.SearchType" json:"searchType,omitempty"`
	Name       string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Keywords   []*Keyword `protobuf:"bytes,3,rep,name=keywords" json:"keywords,omitempty"`
	Kind       Kind       `protobuf:"varint,4,opt,name=kind,enum=contextionary.Kind" json:"kind,omitempty"`
	Certainty  float32    `protobuf:"fixed32,5,opt,name=certainty" json:"certainty,omitempty"`
}

func (m *SchemaSearchParams) Reset()                    { *m = SchemaSearchParams{} }
func (m *SchemaSearchParams) String() string            { return proto.CompactTextString(m) }
func (*SchemaSearchParams) ProtoMessage()               {}
func (*SchemaSearchParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SchemaSearchParams) GetSearchType() SearchType {
	if m != nil {
		return m.SearchType
	}
	return SearchType_CLASS
}

func (m *SchemaSearchParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchemaSearchParams) GetKeywords() []*Keyword {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func (m *SchemaSearchParams) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_THING
}

func (m *SchemaSearchParams) GetCertainty() float32 {
	if m != nil {
		return m.Certainty
	}
	return 0
}

type SchemaSearchResults struct {
	Type    SearchType            `protobuf:"varint,1,opt,name=type,enum=contextionary.SearchType" json:"type,omitempty"`
	Results []*SchemaSearchResult `protobuf:"bytes,2,rep,name=results" json:"results,omitempty"`
}

func (m *SchemaSearchResults) Reset()                    { *m = SchemaSearchResults{} }
func (m *SchemaSearchResults) String() string            { return proto.CompactTextString(m) }
func (*SchemaSearchResults) ProtoMessage()               {}
func (*SchemaSearchResults) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SchemaSearchResults) GetType() SearchType {
	if m != nil {
		return m.Type
	}
	return SearchType_CLASS
}

func (m *SchemaSearchResults) GetResults() []*SchemaSearchResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type SchemaSearchResult struct {
	Name      string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Kind      Kind    `protobuf:"varint,2,opt,name=kind,enum=contextionary.Kind" json:"kind,omitempty"`
	Certainty float32 `protobuf:"fixed32,3,opt,name=certainty" json:"certainty,omitempty"`
}

func (m *SchemaSearchResult) Reset()                    { *m = SchemaSearchResult{} }
func (m *SchemaSearchResult) String() string            { return proto.CompactTextString(m) }
func (*SchemaSearchResult) ProtoMessage()               {}
func (*SchemaSearchResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SchemaSearchResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SchemaSearchResult) GetKind() Kind {
	if m != nil {
		return m.Kind
	}
	return Kind_THING
}

func (m *SchemaSearchResult) GetCertainty() float32 {
	if m != nil {
		return m.Certainty
	}
	return 0
}

func init() {
	proto.RegisterType((*Word)(nil), "contextionary.Word")
	proto.RegisterType((*WordPresent)(nil), "contextionary.WordPresent")
	proto.RegisterType((*WordStopword)(nil), "contextionary.WordStopword")
	proto.RegisterType((*Keyword)(nil), "contextionary.Keyword")
	proto.RegisterType((*SchemaSearchParams)(nil), "contextionary.SchemaSearchParams")
	proto.RegisterType((*SchemaSearchResults)(nil), "contextionary.SchemaSearchResults")
	proto.RegisterType((*SchemaSearchResult)(nil), "contextionary.SchemaSearchResult")
	proto.RegisterEnum("contextionary.SearchType", SearchType_name, SearchType_value)
	proto.RegisterEnum("contextionary.Kind", Kind_name, Kind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Contextionary service

type ContextionaryClient interface {
	IsWordStopword(ctx context.Context, in *Word, opts ...grpc.CallOption) (*WordStopword, error)
	IsWordPresent(ctx context.Context, in *Word, opts ...grpc.CallOption) (*WordPresent, error)
	SchemaSearch(ctx context.Context, in *SchemaSearchParams, opts ...grpc.CallOption) (*SchemaSearchResults, error)
}

type contextionaryClient struct {
	cc *grpc.ClientConn
}

func NewContextionaryClient(cc *grpc.ClientConn) ContextionaryClient {
	return &contextionaryClient{cc}
}

func (c *contextionaryClient) IsWordStopword(ctx context.Context, in *Word, opts ...grpc.CallOption) (*WordStopword, error) {
	out := new(WordStopword)
	err := grpc.Invoke(ctx, "/contextionary.Contextionary/IsWordStopword", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextionaryClient) IsWordPresent(ctx context.Context, in *Word, opts ...grpc.CallOption) (*WordPresent, error) {
	out := new(WordPresent)
	err := grpc.Invoke(ctx, "/contextionary.Contextionary/IsWordPresent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contextionaryClient) SchemaSearch(ctx context.Context, in *SchemaSearchParams, opts ...grpc.CallOption) (*SchemaSearchResults, error) {
	out := new(SchemaSearchResults)
	err := grpc.Invoke(ctx, "/contextionary.Contextionary/SchemaSearch", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Contextionary service

type ContextionaryServer interface {
	IsWordStopword(context.Context, *Word) (*WordStopword, error)
	IsWordPresent(context.Context, *Word) (*WordPresent, error)
	SchemaSearch(context.Context, *SchemaSearchParams) (*SchemaSearchResults, error)
}

func RegisterContextionaryServer(s *grpc.Server, srv ContextionaryServer) {
	s.RegisterService(&_Contextionary_serviceDesc, srv)
}

func _Contextionary_IsWordStopword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Word)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextionaryServer).IsWordStopword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contextionary.Contextionary/IsWordStopword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextionaryServer).IsWordStopword(ctx, req.(*Word))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contextionary_IsWordPresent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Word)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextionaryServer).IsWordPresent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contextionary.Contextionary/IsWordPresent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextionaryServer).IsWordPresent(ctx, req.(*Word))
	}
	return interceptor(ctx, in, info, handler)
}

func _Contextionary_SchemaSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemaSearchParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContextionaryServer).SchemaSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/contextionary.Contextionary/SchemaSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContextionaryServer).SchemaSearch(ctx, req.(*SchemaSearchParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contextionary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "contextionary.Contextionary",
	HandlerType: (*ContextionaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsWordStopword",
			Handler:    _Contextionary_IsWordStopword_Handler,
		},
		{
			MethodName: "IsWordPresent",
			Handler:    _Contextionary_IsWordPresent_Handler,
		},
		{
			MethodName: "SchemaSearch",
			Handler:    _Contextionary_SchemaSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contextionary.proto",
}

func init() { proto.RegisterFile("contextionary.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 454 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdd, 0x6e, 0xd3, 0x30,
	0x14, 0xc7, 0xe3, 0x36, 0xeb, 0xc7, 0x59, 0x3b, 0x55, 0xa7, 0xd2, 0x64, 0x02, 0x48, 0xc5, 0x12,
	0x5a, 0x55, 0x89, 0x5d, 0x94, 0x2b, 0xb4, 0xab, 0x51, 0x10, 0x54, 0xa0, 0xad, 0x72, 0x2a, 0x4d,
	0x5c, 0x86, 0xd6, 0xa2, 0xd1, 0x68, 0x1c, 0xd9, 0x46, 0x23, 0x97, 0xbc, 0x28, 0x0f, 0xc1, 0x13,
	0xa0, 0x38, 0x1f, 0x4b, 0x42, 0x05, 0xec, 0xee, 0x9c, 0xe3, 0xff, 0xf9, 0xf8, 0x1d, 0xdb, 0x30,
	0xde, 0xc8, 0xc8, 0x88, 0xef, 0x26, 0x94, 0x51, 0xa0, 0x92, 0xf3, 0x58, 0x49, 0x23, 0x71, 0x58,
	0x0b, 0x32, 0x0f, 0xdc, 0x1b, 0xa9, 0xb6, 0x88, 0xe0, 0xde, 0x49, 0xb5, 0xa5, 0x64, 0x42, 0xa6,
	0x7d, 0x6e, 0x6d, 0x76, 0x06, 0xc7, 0xe9, 0xd9, 0x4a, 0x09, 0x2d, 0x22, 0x83, 0x14, 0xba, 0x71,
	0x66, 0x5a, 0x55, 0x8f, 0x17, 0x2e, 0x9b, 0xc1, 0x20, 0x15, 0xfa, 0x46, 0xc6, 0x69, 0x22, 0x7a,
	0xd0, 0xd3, 0xb9, 0x9d, 0x4b, 0x4b, 0x9f, 0x5d, 0x40, 0xf7, 0x83, 0x48, 0xac, 0x8c, 0x42, 0xf7,
	0x36, 0x33, 0xf3, 0xb6, 0x85, 0x8b, 0xa7, 0xd0, 0xb9, 0x13, 0xe1, 0x97, 0x9d, 0xa1, 0xad, 0x09,
	0x99, 0xb6, 0x78, 0xee, 0xb1, 0x9f, 0x04, 0xd0, 0xdf, 0xec, 0xc4, 0x3e, 0xf0, 0x45, 0xa0, 0x36,
	0xbb, 0x55, 0xa0, 0x82, 0xbd, 0xc6, 0x57, 0x00, 0xda, 0xfa, 0xeb, 0x24, 0x16, 0xb6, 0xd6, 0xc9,
	0xfc, 0xd1, 0x79, 0x9d, 0xde, 0x2f, 0x05, 0xbc, 0x22, 0x4e, 0xb9, 0xa3, 0x60, 0x2f, 0x6c, 0x9f,
	0x3e, 0xb7, 0x36, 0xce, 0xa1, 0x97, 0x0f, 0xa2, 0x69, 0x7b, 0xd2, 0x9e, 0x1e, 0xcf, 0x4f, 0x1b,
	0xc5, 0x72, 0x02, 0x5e, 0xea, 0xf0, 0x0c, 0xdc, 0xdb, 0x30, 0xda, 0x52, 0xd7, 0x36, 0x1f, 0x37,
	0xf5, 0x61, 0xb4, 0xe5, 0x56, 0x80, 0x4f, 0xa0, 0xbf, 0x11, 0xca, 0x04, 0x61, 0x64, 0x12, 0x7a,
	0x64, 0xe9, 0xee, 0x03, 0xec, 0x07, 0x81, 0x71, 0x15, 0x90, 0x0b, 0xfd, 0xed, 0xab, 0xd1, 0xf8,
	0x02, 0x5c, 0xf3, 0x5f, 0x6c, 0x56, 0x86, 0x17, 0xd0, 0x55, 0x59, 0x26, 0x6d, 0x59, 0x80, 0x67,
	0xcd, 0x8c, 0x3f, 0x7a, 0xf0, 0x22, 0x83, 0xc9, 0xfa, 0x8e, 0xb3, 0xe3, 0x72, 0x51, 0xa4, 0xb2,
	0xa8, 0x02, 0xba, 0xf5, 0x20, 0xe8, 0x76, 0x03, 0x7a, 0xf6, 0x1c, 0xe0, 0x9e, 0x00, 0xfb, 0x70,
	0xb4, 0xf8, 0x78, 0xe9, 0xfb, 0x23, 0x07, 0x07, 0xd0, 0x5b, 0xf1, 0xeb, 0xd5, 0x5b, 0xbe, 0xfe,
	0x34, 0x22, 0xb3, 0xa7, 0xe0, 0xa6, 0x25, 0x53, 0xc1, 0xfa, 0xfd, 0xf2, 0xea, 0xdd, 0xc8, 0x41,
	0x80, 0xce, 0xe5, 0x62, 0xbd, 0xbc, 0xbe, 0x1a, 0x91, 0xf9, 0x2f, 0x02, 0xc3, 0x45, 0x75, 0x00,
	0x7c, 0x03, 0x27, 0x4b, 0x5d, 0x7b, 0x98, 0xcd, 0x11, 0xd3, 0x43, 0xef, 0xf1, 0x81, 0x60, 0x91,
	0xc1, 0x1c, 0x7c, 0x0d, 0xc3, 0xac, 0x4a, 0xf1, 0x0f, 0x0e, 0x16, 0xf1, 0x0e, 0x04, 0xf3, 0x04,
	0xe6, 0xe0, 0x0d, 0x0c, 0xaa, 0x2b, 0xc5, 0xbf, 0x5d, 0x47, 0xf6, 0xa6, 0x3d, 0xf6, 0xcf, 0x1b,
	0xd3, 0xcc, 0xf9, 0xdc, 0xb1, 0x9f, 0xfa, 0xe5, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0xa8,
	0x83, 0x1d, 0xeb, 0x03, 0x00, 0x00,
}
