name: Create Release

on:
  push:
    tags:
      - '**'

jobs:
  create-release:
    name: Create Release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: en
            model_version: 0.16.0
          # - language: nl
          #   model_version: 0.16.0
          # - language: en
          #   model_version: 0.14.0
          # - language: nl
          #   model_version: 0.14.0
          # - language: de
          #   model_version: 0.14.0
          # - language: cs
          #   model_version: 0.14.0
          # - language: it
          #   model_version: 0.14.0
    env:
      DOCKER_ORG: semitechnologies
      DOCKER_REPO: contextionary
      LANGUAGE: ${{matrix.language}}
      MODEL_VERSION: ${{matrix.model_version}}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Build and release
        run: |
          export SOFTWARE_VERSION=${GITHUB_REF##*/}
          set -e
          ./prepare_docker_buildx.sh
          PUSH_MULTIARCH=1 ./build.sh
          echo "Success"
  gh-release:
    name: Create a GitHub Release
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          draft: true
