name: Tests

on:
  push:
    branches:
      - master
    tags:
      - '**'
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - model_version: 0.16.0
            dimensions: 300
          - model_version: 0.14.0
            dimensions: 600
    env:
      DOCKER_ORG: semitechnologies
      DOCKER_REPO: contextionary
      LANGUAGE: en
      SOFTWARE_VERSION: localtest
      MODEL_VERSION: ${{matrix.model_version}}
      DIMENSIONS: ${{matrix.dimensions}}
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ !github.event.pull_request.head.repo.fork }}
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          cache: true
      - name: Build and run journey tests
        run: |
          set -e
          docker buildx version
          ./build.sh
          ./test/journey.sh
          echo "Success"
